name: Update vscode-html-languageservice

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31

      - name: Update
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          nix run nixpkgs#nix-update -- --flake --commit vscode-html-languageservice

      - name: Open PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff HEAD~1 --quiet || \
            git push origin "HEAD:refs/heads/bump/vscode-html-languageservice" --force && \
            gh pr create \
              --head "bump/vscode-html-languageservice" \
              --title "vscode-html-languageservice: $(nix eval .#vscode-html-languageservice.version --raw)" \
              --body "Automated version bump by [nix-update](https://github.com/Mic92/nix-update)." \
              || true
